# Generated by Django 4.2.3 on 2023-07-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_proce',
            new_name='product_price',
        ),
    ]
